language: python
python:
  - "3.7"
env:
  - ORT_RELEASE=onnxruntime_dist_cpu VENV_PATH='' PYTEST_ARGS="--cov=daceml --cov-report=term --cov-report xml --cov-config=.coveragerc"
install:
  - wget https://github.com/orausch/onnxruntime/releases/download/build1/onnxruntime_dist_cpu.tar.gz
  - tar -xzf onnxruntime_dist_cpu.tar.gz
  - make install
  - pip install codecov pytest-cov
script:
  - make test
  - codecov
  - make check-formatting
